JieBa:
    url: src/main/resources/fkck.txt
device:
    file:
        url: src/main/resources/video/device/
fault:
    file:
        url: src/main/resources/video/fault/
server:
    port: 9123
sop:
    file:
        url: src/main/resources/video/sop/
spring:
    data:
        neo4j:
            password: QSJ13977690929
            uri: bolt://8.134.192.208:7687
            username: neo4j
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: QSJ13977690929
        url: jdbc:mysql://8.134.192.208:3306/industrial_db?serverTimezone=UTC
        username: root
    mail:
        default-encoding: UTF-8
        host: smtp.qq.com
        password: udislrneaigtebbi
        port: 587
        username: 2548054679@qq.com
    redis:
        database: 0
        host: localhost
        password: '123456'
        port: 6379
    servlet:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1024MB
Dify:
    api: http://8.134.192.208
    key: Bearer app-B0s7FDkvmuVwNQSJgsIIiDpS

v1:
#    1为腾讯向量库和百川，2为Milvus和ChatGLM
    ChooseDBAndModel: 2
